Project3_Kittens/kittens/config/routes.rb
Rails.application.routes.draw do

    resources :kittens
    root 'kittens#index'

end

Project3_Kittens/kittens/app/models/kitten.rb
class Kitten < ActiveRecord::Base
end

Project3_Kittens/kittens/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Project3_Kittens/kittens/app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  def index
    @kittens = Kitten.all
    respond_to do |format|
        format.html
        format.json {render json: @kittens}
    end
  end

  def new
    @kitten = Kitten.new
  end

  def create
    @kitten = Kitten.new(kitten_params)
    if @kitten.save
        redirect_to @kitten, notice: "Kitten created"
    else
        render 'new'
    end
  end

  def edit
    @kitten = Kitten.find(params[:id])
  end

  def update
    @kitten = Kitten.find(params[:id])
    respond_to do |format|
        if @kitten.update(kitten_params)
            redirect_to @kitten, notice: 'Kitten updated'
        else
            render 'edit'
        end
    end
  end

  def show
    @kitten = Kitten.find(params[:id])
    respond_to do |format|
        format.html
        format.json {render json: @kitten}
    end
  end

  def destroy
    @kitten = Kitten.find(params[:id])
    @kitten.destroy
    redirect_to root_url
  end

  private
    def kitten_params
        params.require(:kitten).permit(:name, :age, :cuteness, :softness)
    end
end

Project3_Kittens/kittens/app/helpers/application_helper.rb
module ApplicationHelper
end

Project3_Kittens/kittens/app/helpers/kittens_helper.rb
module KittensHelper
end

Project3_Kittens/kittens/app/views/kittens/_form.html.erb
<%= form_for @kitten do |f| %>

    <div>
        <%= f.label :name %>
        <%= f.text_field :name %>
    </div>

    <div>
        <%= f.label :age %>
        <%= f.number_field :age %>
    </div>

    <div>
        <%= f.label :cuteness %>
        <%= f.number_field :cuteness, in: 1..10 %>
    </div>

    <div>
        <%= f.label :softness %>
        <%= f.number_field :softness, in: 1..10 %>
    </div>

    <p>
        <%= f.submit "Yay for kittens!" %>
    </p>

<% end %>

Project3_Kittens/kittens/app/views/kittens/edit.html.erb
<h1>Edit kitten!</h1>

<%= render 'form' %>

<%= link_to 'Back', kittens_path %>

Project3_Kittens/kittens/app/views/kittens/index.html.erb
<h1>All kittens</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Cuteness</th>
      <th>Softness</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @kittens.each do |kitten| %>
      <tr>
        <td><%= kitten.name %></td>
        <td><%= kitten.age %></td>
        <td><%= kitten.cuteness %></td>
        <td><%= kitten.softness %></td>
        <td><%= link_to 'Show', kitten %></td>
        <td><%= link_to 'Edit', edit_kitten_path(kitten) %></td>
        <td><%= link_to 'Destroy', kitten, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br />
<%= link_to 'New Kitten', new_kitten_path %>

Project3_Kittens/kittens/app/views/kittens/new.html.erb
<h1>New kitten!</h1>

<%= render 'form' %>

<%= link_to 'Back', kittens_path %>

Project3_Kittens/kittens/app/views/kittens/show.html.erb
<h1>Kitten <%= @kitten.name %> !</h1>
<p>
    <%= @kitten.name %>
</p>
<p>
    <%= @kitten.age %>
</p>
<p>
    <%= @kitten.cuteness %>
</p>
<p>
    <%= @kitten.softness %>
</p>

<%= link_to 'Delete kitten', kitten_path(@kitten), method: :delete %>